# Generated by Django 3.0.5 on 2020-04-21 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, help_text="It's always nice to add a friendly message!", max_length=300, verbose_name='Optional Message')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(help_text='Please select the user yoy want to play the game with', on_delete=django.db.models.deletion.CASCADE, related_name='invitation_recieved', to=settings.AUTH_USER_MODEL, verbose_name='User to invite')),
            ],
        ),
    ]
